# Generated by Django 4.2.4 on 2023-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=20)),
                ('Student_roll', models.IntegerField()),
                ('student_marks', models.FloatField()),
            ],
        ),
    ]
